etc: fix volumeMounts.mountPath syntax
The make podman-dev-up command was failing:

...

error starting container 7690dbc3f7b4da3f5b001bb5bdc217932499ecd726ba75ee7f1fc5270938a79e: workdir "/src/claircore/cmd/libindexhttp" does not exist on container 7690dbc3f7b4da3f5b001bb5bdc217932499ecd726ba75ee7f1fc5270938a79e
error starting container 9273f96e1fc6dc7d85b987e99e702d5aac8bde03cbb6935eb6f7fcb81ee5db70: workdir "/src/claircore/cmd/libvulnhttp" does not exist on container 9273f96e1fc6dc7d85b987e99e702d5aac8bde03cbb6935eb6f7fcb81ee5db70

Error: failed to start 2 containers
make: *** [Makefile:81: podman-dev-up] Error 125